package de.ebertp.HomeDroid.Model;


import android.content.Context;

import com.j256.ormlite.field.DatabaseField;

import java.sql.SQLException;
import java.util.List;

import de.ebertp.HomeDroid.DbAdapter.BaseDbAdapter;
import de.ebertp.HomeDroid.HomeDroidApp;
import de.ebertp.HomeDroid.Utils.PrefixHelper;

public class HmSpeechCommand {

    private static final String COLUMN_ROWID = "rowid";

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    Integer id;
    @DatabaseField
    int rowId;

    //HMCommand types
    @DatabaseField
    int type;
    @DatabaseField
    String value;
    @DatabaseField
    String command;
    @DatabaseField
    String name;

    public HmSpeechCommand() {

    }

    public HmSpeechCommand(int rowId, int type, String value, String command) {
        this.rowId = rowId;
        this.type = type;
        this.value = value;
        this.command = command;
        this.name = "";
    }

    public static List<HmSpeechCommand> getCommandsForCurrentPrefix(Context ctx) throws SQLException {

        int prefix = PrefixHelper.getPrefix(ctx);
        int low = prefix * BaseDbAdapter.PREFIX_OFFSET;
        int high = (prefix + 1) * BaseDbAdapter.PREFIX_OFFSET;

        return HomeDroidApp.db()
                .getSpeechCommandDao()
                .queryBuilder()
                .where()
                .between(HmSpeechCommand.COLUMN_ROWID, low, high)
                .query();

    }

    public int getRowId() {
        return rowId;
    }

    public void setRowId(int rowId) {
        this.rowId = rowId;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getCommand() {
        return command;
    }

    public void setCommand(String command) {
        this.command = command;
    }

    @Override
    public String toString() {
        return getCommand();
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }
}
