package de.ebertp.HomeDroid.Model;

import com.j256.ormlite.field.DatabaseField;

public class WebCam extends HMObject {

    public static final int TYPE_JPEG = 0;
    public static final int TYPE_MPEG = 1;

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    Integer id;

    @DatabaseField
    String name;

    @DatabaseField
    String url;

    @DatabaseField
    int type;

    @DatabaseField
    String authUser;

    @DatabaseField
    String authPass;

    public WebCam() {

    }

    public WebCam(String name, String url, int type) {
        this.name = name;
        this.url = url;
        this.type = type;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getAuthUser() {
        return authUser;
    }

    public void setAuthUser(String authUser) {
        this.authUser = authUser;
    }

    public String getAuthPass() {
        return authPass;
    }

    public void setAuthPass(String authPass) {
        this.authPass = authPass;
    }

    @Override
    public String toString() {
        return name;
    }
}
